export default{
    urlList:{
        all:[
            {
                img:'https://coding-pages-bucket-3501976-8144565-8415-426016-1304571732.cos.ap-beijing.myqcloud.com/tools-logo/tuya.jpg',
                url:'https://tuya.xinxiao.tech/',
                name:'图压',
                details:'国内的免费图片压缩工具',
                type:'img'
            },
            {
                img:'https://s.pinimg.com/webapp/favicon-54a5b2af.png',
                url:'https://www.pinterest.co.uk/',
                name:'pinterest',
                details:'国外花瓣网（需要翻墙）',
                type:'img'
            },
            {
                img:'https://coding-pages-bucket-3501976-8144565-8415-426016-1304571732.cos.ap-beijing.myqcloud.com/tools-logo/Freellustrations.jpg',
                url:'https://coolbackgrounds.io/',
                name:'Cool Background',
                details:'生产很棒的背景图片',
                type:'img'
            },
            {
                img:'https://coding-pages-bucket-3501976-8144565-8415-426016-1304571732.cos.ap-beijing.myqcloud.com/tools-logo/coolbackgrounds.jpg',
                url:'https://freellustrations.com/',
                name:'Freellustrations',
                details:'插画风背景图片',
                type:'img'
            },
            {
                img:'https://www.runoob.com/favicon.ico',
                url:'https://www.runoob.com/',
                name:'菜鸟教程',
                details:'学习编程基础的网站',
                type:'code'
            },
            {
                img:'https://www.imooc.com/favicon.ico',
                url:'https://www.imooc.com/',
                name:'慕课网',
                details:'学习编程基础的网站',
                type:'code'
            },
            {
                img:'https://element.eleme.cn/favicon.ico',
                url:'https://element.eleme.cn/#/zh-CN',
                name:'Element-ui',
                details:'Vue的UI库',
                type:'code'
            },
            {
                img:'https://www.iconfont.cn/favicon.ico',
                url:'https://www.iconfont.cn/',
                name:'iconfont',
                details:'阿里巴巴提供的免费icon图标',
                type:'code'
            },
            {
                img:'https://g.csdnimg.cn/static/logo/favicon32.ico',
                url:'https://www.csdn.net/',
                name:'csdn',
                details:'程序员社区',
                type:'code'
            },
            {
                img:'https://juejin.cn/favicon.ico',
                url:'https://juejin.cn/',
                name:'掘金',
                details:'程序员社区',
                type:'code'
            },
            {
                img:'https://gitee.com/favicon.ico',
                url:'https://gitee.com/',
                name:'码云',
                details:'国产github，代码管理平台',
                type:'code'
            },
            {
                img:'https://carbon.now.sh/favicon.ico',
                url:'https://carbon.now.sh/',
                name:'carbon',
                details:'把“代码块”拍成张照片',
                type:'code'
            },
            {
                img:'http://www.doyoudo.com/favicon.ico',
                url:'http://www.doyoudo.com/',
                name:'doyoudo',
                details:'学习ps,pr的有趣网站',
                type:'design'
            },
            {
                img:'https://huaban.com/favicon.ico',
                url:'https://huaban.com/',
                name:'花瓣网',
                details:'很多设计的图片',
                type:'design'
            },
            {
                img:'http://www.tan8.com/favicon.ico',
                url:'http://www.tan8.com/',
                name:'弹琴吧',
                details:'钢琴谱等...',
                type:'music'
            },
            {
                img:'https://www.artstation.com/favicon.ico',
                url:'https://www.artstation.com/',
                name:'Artstation',
                details:'A站，各种大神的画！（需要翻墙）',
                type:'drawing'
            },
            {
                img:'https://www.pixiv.net/favicon.ico',
                url:'https://www.pixiv.net/',
                name:'Pixiv',
                details:'2号P站（需要翻墙）',
                type:'drawing'
            },
            {
                img:'https://www.80s.tw/favicon.ico',
                url:'https://www.80s.tw/',
                name:'80s',
                details:'各种盗版电影',
                type:'movie'
            },
            {
                img:'https://xxggg.gitee.io//favicon.ico',
                url:'https://xxggg.gitee.io/',
                name:'谢夏戈的博客',
                details:'谢夏戈的gitee博客',
                type:'mark'
            },
            {
                img:'https://xxggg.github.io//favicon.ico',
                url:'https://xxggg.github.io/',
                name:'谢夏戈的博客',
                details:'谢夏戈的github博客',
                type:'mark'
            },
        ]
    }
}